---
# Installs required system packages
- name: Update cache
  apt: update_cache=yes

- name: Install system packages
  apt: name="{{item}}" update_cache=yes state=present
  with_items:
      - "{{ system_packages }}"

- name: Update pip
  pip: name=pip state=latest

- name: Make sure the latest npm is installed
  npm: name=npm global=true

- name: Install Bower globally.
  npm: name=bower global=yes

- name: Install Gulp globally.
  npm: name=gulp global=yes
